development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:0db4ef616c034fd1d95a64447623973e@sole.redistogo.com:9976/
  channel_prefix: message_me_production
